// 副本模板种子数据
// 从前端 src/data/combat/dungeons.ts 迁移

export const dungeonTemplatesData = [
  // ==================== 第1章：青云山脉 ====================
  {
    dungeonId: '1-1',
    name: '山脚小径',
    description: '山脚下的小路，偶有野兽出没',
    type: 'story',
    chapterId: '1',
    stages: JSON.stringify([{ level: 1, enemyIds: ['wild_boar'], rewards: { exp: 20, spiritStones: 5, drops: [] } }]),
    requirements: JSON.stringify({ requiredLevel: 1 }),
    energyCost: 5,
    dailyLimit: null,
    recommendedPower: null,
    order: 1,
  },
  {
    dungeonId: '1-2',
    name: '密林深处',
    description: '茂密的树林中藏着灵狼',
    type: 'story',
    chapterId: '1',
    stages: JSON.stringify([{ level: 2, enemyIds: ['wild_boar', 'spirit_wolf'], rewards: { exp: 40, spiritStones: 10, drops: [] } }]),
    requirements: JSON.stringify({ requiredLevel: 2 }),
    energyCost: 6,
    dailyLimit: null,
    recommendedPower: null,
    order: 2,
  },
  {
    dungeonId: '1-3',
    name: '狼王巢穴',
    description: '灵狼群的栖息地',
    type: 'story',
    chapterId: '1',
    stages: JSON.stringify([{ level: 3, enemyIds: ['spirit_wolf', 'spirit_wolf'], rewards: { exp: 60, spiritStones: 20, drops: [] } }]),
    requirements: JSON.stringify({ requiredLevel: 3 }),
    energyCost: 8,
    dailyLimit: null,
    recommendedPower: null,
    order: 3,
  },

  // ==================== 第2章：焰火洞窟 ====================
  {
    dungeonId: '2-1',
    name: '洞窟入口',
    description: '洞口热浪滚滚',
    type: 'story',
    chapterId: '2',
    stages: JSON.stringify([{ level: 4, enemyIds: ['fire_serpent'], rewards: { exp: 80, spiritStones: 30, drops: [] } }]),
    requirements: JSON.stringify({ requiredLevel: 4 }),
    energyCost: 10,
    dailyLimit: null,
    recommendedPower: null,
    order: 4,
  },
  {
    dungeonId: '2-2',
    name: '熔岩通道',
    description: '流淌着岩浆的通道',
    type: 'story',
    chapterId: '2',
    stages: JSON.stringify([{ level: 5, enemyIds: ['fire_serpent', 'fire_serpent'], rewards: { exp: 100, spiritStones: 40, drops: [] } }]),
    requirements: JSON.stringify({ requiredLevel: 5 }),
    energyCost: 12,
    dailyLimit: null,
    recommendedPower: null,
    order: 5,
  },
  {
    dungeonId: '2-3',
    name: '火蛇巢穴',
    description: '火蛇聚集之地',
    type: 'story',
    chapterId: '2',
    stages: JSON.stringify([{ level: 6, enemyIds: ['fire_serpent', 'fire_serpent', 'fire_serpent'], rewards: { exp: 150, spiritStones: 60, drops: [] } }]),
    requirements: JSON.stringify({ requiredLevel: 6 }),
    energyCost: 15,
    dailyLimit: null,
    recommendedPower: null,
    order: 6,
  },

  // ==================== 第3章：岩石峡谷 ====================
  {
    dungeonId: '3-1',
    name: '峡谷入口',
    description: '巨石林立的峡谷',
    type: 'story',
    chapterId: '3',
    stages: JSON.stringify([{ level: 7, enemyIds: ['rock_golem'], rewards: { exp: 180, spiritStones: 80, drops: [] } }]),
    requirements: JSON.stringify({ requiredLevel: 7 }),
    energyCost: 18,
    dailyLimit: null,
    recommendedPower: null,
    order: 7,
  },
  {
    dungeonId: '3-2',
    name: '傀儡墓地',
    description: '废弃的傀儡残骸遍布',
    type: 'story',
    chapterId: '3',
    stages: JSON.stringify([{ level: 8, enemyIds: ['rock_golem', 'rock_golem'], rewards: { exp: 220, spiritStones: 100, drops: [] } }]),
    requirements: JSON.stringify({ requiredLevel: 8 }),
    energyCost: 20,
    dailyLimit: null,
    recommendedPower: null,
    order: 8,
  },
  {
    dungeonId: '3-3',
    name: '傀儡工坊',
    description: '上古时期制造傀儡的遗址',
    type: 'story',
    chapterId: '3',
    stages: JSON.stringify([{ level: 9, enemyIds: ['rock_golem', 'rock_golem', 'wandering_cultivator'], rewards: { exp: 300, spiritStones: 150, drops: [] } }]),
    requirements: JSON.stringify({ requiredLevel: 9 }),
    energyCost: 25,
    dailyLimit: null,
    recommendedPower: null,
    order: 9,
  },

  // ==================== 第4章：金丹试炼场 ====================
  {
    dungeonId: '4-1',
    name: '火蝎巢穴',
    description: '灼热的洞穴中栖息着大量火焰蝎',
    type: 'story',
    chapterId: '4',
    stages: JSON.stringify([{ level: 13, enemyIds: ['fire_scorpion', 'fire_scorpion'], rewards: { exp: 500, spiritStones: 200, drops: [{ itemId: 'fire_scorpion_venom', chance: 0.5, quantity: 1 }, { itemId: 'healing_pill_jindan', chance: 0.2, quantity: 1 }] } }]),
    requirements: JSON.stringify({ requiredLevel: 13 }),
    energyCost: 30,
    dailyLimit: null,
    recommendedPower: null,
    order: 10,
  },
  {
    dungeonId: '4-2',
    name: '雷云之巅',
    description: '云层之上的雷鹰领地',
    type: 'story',
    chapterId: '4',
    stages: JSON.stringify([{ level: 15, enemyIds: ['golden_crab', 'thunder_eagle'], rewards: { exp: 700, spiritStones: 300, drops: [{ itemId: 'golden_crab_shell', chance: 0.4, quantity: 1 }, { itemId: 'thunder_eagle_feather', chance: 0.4, quantity: 1 }] } }]),
    requirements: JSON.stringify({ requiredLevel: 15 }),
    energyCost: 35,
    dailyLimit: null,
    recommendedPower: null,
    order: 11,
  },
  {
    dungeonId: '4-3',
    name: '金丹散修据点',
    description: '金丹散修盘踞的山寨',
    type: 'story',
    chapterId: '4',
    stages: JSON.stringify([{ level: 17, enemyIds: ['thunder_eagle', 'jindan_cultivator'], rewards: { exp: 1000, spiritStones: 500, drops: [{ itemId: 'jindan_pill', chance: 0.1, quantity: 1 }] } }]),
    requirements: JSON.stringify({ requiredLevel: 17 }),
    energyCost: 40,
    dailyLimit: null,
    recommendedPower: null,
    order: 12,
  },

  // ==================== 第5章：元婴秘境 ====================
  {
    dungeonId: '5-1',
    name: '幽冥蛇窟',
    description: '秘境入口被冥蛇盘踞',
    type: 'story',
    chapterId: '5',
    stages: JSON.stringify([{ level: 19, enemyIds: ['dark_serpent', 'dark_serpent'], rewards: { exp: 1200, spiritStones: 500, drops: [{ itemId: 'snake_gallbladder', chance: 0.4, quantity: 1 }] } }]),
    requirements: JSON.stringify({ requiredLevel: 19 }),
    energyCost: 45,
    dailyLimit: null,
    recommendedPower: null,
    order: 13,
  },
  {
    dungeonId: '5-2',
    name: '噬魂蝠洞',
    description: '秘境深处的蝠洞',
    type: 'story',
    chapterId: '5',
    stages: JSON.stringify([{ level: 21, enemyIds: ['soul_bat', 'millennium_treant'], rewards: { exp: 1800, spiritStones: 800, drops: [{ itemId: 'soul_crystal', chance: 0.3, quantity: 1 }] } }]),
    requirements: JSON.stringify({ requiredLevel: 21 }),
    energyCost: 50,
    dailyLimit: null,
    recommendedPower: null,
    order: 14,
  },
  {
    dungeonId: '5-3',
    name: '秘境核心',
    description: '秘境最深处，元婴老怪守护着远古宝藏',
    type: 'story',
    chapterId: '5',
    stages: JSON.stringify([{ level: 23, enemyIds: ['soul_bat', 'yuanying_elder'], rewards: { exp: 2500, spiritStones: 1200, drops: [{ itemId: 'yuanying_pill', chance: 0.05, quantity: 1 }] } }]),
    requirements: JSON.stringify({ requiredLevel: 23 }),
    energyCost: 60,
    dailyLimit: null,
    recommendedPower: null,
    order: 15,
  },

  // ==================== 第6章：化神修罗场 ====================
  {
    dungeonId: '6-1',
    name: '修罗前哨',
    description: '修罗场的入口，修罗战士与炎魔把守此处',
    type: 'story',
    chapterId: '6',
    stages: JSON.stringify([{ level: 25, enemyIds: ['shura_warrior', 'flame_demon'], rewards: { exp: 3000, spiritStones: 1500, drops: [{ itemId: 'shura_blood', chance: 0.5, quantity: 1 }] } }]),
    requirements: JSON.stringify({ requiredLevel: 25 }),
    energyCost: 65,
    dailyLimit: null,
    recommendedPower: null,
    order: 16,
  },
  {
    dungeonId: '6-2',
    name: '血战沙场',
    description: '修罗将军率领的精锐战场',
    type: 'story',
    chapterId: '6',
    stages: JSON.stringify([{ level: 26, enemyIds: ['shura_general', 'golden_puppet'], rewards: { exp: 4500, spiritStones: 2500, drops: [{ itemId: 'shura_blood', chance: 0.6, quantity: 2 }] } }]),
    requirements: JSON.stringify({ requiredLevel: 26 }),
    energyCost: 75,
    dailyLimit: null,
    recommendedPower: null,
    order: 17,
  },
  {
    dungeonId: '6-3',
    name: '修罗王座',
    description: '修罗王的王座所在',
    type: 'story',
    chapterId: '6',
    stages: JSON.stringify([{ level: 28, enemyIds: ['flame_demon', 'shura_king'], rewards: { exp: 6000, spiritStones: 3500, drops: [{ itemId: 'shura_blood', chance: 1.0, quantity: 3 }, { itemId: 'huashen_pill', chance: 0.03, quantity: 1 }] } }]),
    requirements: JSON.stringify({ requiredLevel: 28 }),
    energyCost: 85,
    dailyLimit: null,
    recommendedPower: null,
    order: 18,
  },

  // ==================== 第7章：合体秘境 ====================
  {
    dungeonId: '7-1',
    name: '雷霆禁地',
    description: '天雷傀儡把守的入口',
    type: 'story',
    chapterId: '7',
    stages: JSON.stringify([{ level: 29, enemyIds: ['thunder_puppet', 'ancient_dragon'], rewards: { exp: 8000, spiritStones: 4000, drops: [{ itemId: 'thunder_essence', chance: 0.3, quantity: 1 }] } }]),
    requirements: JSON.stringify({ requiredLevel: 29 }),
    energyCost: 90,
    dailyLimit: null,
    recommendedPower: null,
    order: 19,
  },
  {
    dungeonId: '7-2',
    name: '九幽魔域',
    description: '九幽魔将盘踞之地',
    type: 'story',
    chapterId: '7',
    stages: JSON.stringify([{ level: 31, enemyIds: ['jiuyou_demon_general', 'chaos_beast'], rewards: { exp: 12000, spiritStones: 6000, drops: [{ itemId: 'soul_crystal', chance: 0.4, quantity: 2 }] } }]),
    requirements: JSON.stringify({ requiredLevel: 31 }),
    energyCost: 100,
    dailyLimit: null,
    recommendedPower: null,
    order: 20,
  },
  {
    dungeonId: '7-3',
    name: '法则之巅',
    description: '合体期大能坐镇之地',
    type: 'story',
    chapterId: '7',
    stages: JSON.stringify([{ level: 32, enemyIds: ['sky_demon', 'heti_powerhouse'], rewards: { exp: 16000, spiritStones: 8000, drops: [{ itemId: 'heti_pill', chance: 0.05, quantity: 1 }] } }]),
    requirements: JSON.stringify({ requiredLevel: 32 }),
    energyCost: 110,
    dailyLimit: null,
    recommendedPower: null,
    order: 21,
  },

  // ==================== 第8章：大乘天劫 ====================
  {
    dungeonId: '8-1',
    name: '仙界前哨',
    description: '仙界守卫镇守的关隘',
    type: 'story',
    chapterId: '8',
    stages: JSON.stringify([{ level: 33, enemyIds: ['immortal_guard', 'void_rift_beast'], rewards: { exp: 18000, spiritStones: 9000, drops: [{ itemId: 'thunder_essence', chance: 0.3, quantity: 1 }] } }]),
    requirements: JSON.stringify({ requiredLevel: 33 }),
    energyCost: 120,
    dailyLimit: null,
    recommendedPower: null,
    order: 22,
  },
  {
    dungeonId: '8-2',
    name: '太古龙巢',
    description: '太古妖龙的巢穴',
    type: 'story',
    chapterId: '8',
    stages: JSON.stringify([{ level: 34, enemyIds: ['ancient_demon_dragon', 'dacheng_cultivator'], rewards: { exp: 22000, spiritStones: 11000, drops: [{ itemId: 'dragon_scale', chance: 0.4, quantity: 2 }] } }]),
    requirements: JSON.stringify({ requiredLevel: 34 }),
    energyCost: 130,
    dailyLimit: null,
    recommendedPower: null,
    order: 23,
  },
  {
    dungeonId: '8-3',
    name: '天劫核心',
    description: '天劫凝聚之地',
    type: 'story',
    chapterId: '8',
    stages: JSON.stringify([{ level: 35, enemyIds: ['tribulation_thunder_avatar', 'dao_enforcer'], rewards: { exp: 28000, spiritStones: 14000, drops: [{ itemId: 'thunder_essence', chance: 0.5, quantity: 2 }, { itemId: 'dacheng_pill', chance: 0.05, quantity: 1 }] } }]),
    requirements: JSON.stringify({ requiredLevel: 35 }),
    energyCost: 140,
    dailyLimit: null,
    recommendedPower: null,
    order: 24,
  },

  // ==================== 第9章：仙界之门 ====================
  {
    dungeonId: '9-1',
    name: '劫雷炼狱',
    description: '无尽劫雷交织的炼狱',
    type: 'story',
    chapterId: '9',
    stages: JSON.stringify([{ level: 35, enemyIds: ['tribulation_guardian', 'tribulation_thunder_avatar'], rewards: { exp: 30000, spiritStones: 15000, drops: [{ itemId: 'thunder_essence', chance: 0.5, quantity: 2 }] } }]),
    requirements: JSON.stringify({ requiredLevel: 35 }),
    energyCost: 150,
    dailyLimit: null,
    recommendedPower: null,
    order: 25,
  },
  {
    dungeonId: '9-2',
    name: '魔君殿堂',
    description: '渡劫魔君的领地',
    type: 'story',
    chapterId: '9',
    stages: JSON.stringify([{ level: 35, enemyIds: ['tribulation_demon_king', 'fallen_true_immortal'], rewards: { exp: 40000, spiritStones: 20000, drops: [{ itemId: 'phoenix_blood', chance: 0.4, quantity: 1 }, { itemId: 'dragon_scale', chance: 0.4, quantity: 2 }] } }]),
    requirements: JSON.stringify({ requiredLevel: 35 }),
    energyCost: 160,
    dailyLimit: null,
    recommendedPower: null,
    order: 26,
  },
  {
    dungeonId: '9-3',
    name: '混沌深渊',
    description: '最终试炼，混沌魔神坐镇，通过者将踏入仙途',
    type: 'story',
    chapterId: '9',
    stages: JSON.stringify([{ level: 36, enemyIds: ['chaos_demon_god'], rewards: { exp: 60000, spiritStones: 30000, drops: [{ itemId: 'chaos_essence', chance: 0.3, quantity: 1 }, { itemId: 'phoenix_blood', chance: 0.5, quantity: 1 }, { itemId: 'dragon_scale', chance: 0.5, quantity: 2 }] } }]),
    requirements: JSON.stringify({ requiredLevel: 36 }),
    energyCost: 200,
    dailyLimit: null,
    recommendedPower: null,
    order: 27,
  },
];
