// 装备模板种子数据

export const equipmentTemplatesData = [
  // ==================== 武器 - 炼气期 ====================
  {
    equipmentId: 'mutou_jian',
    name: '木剑',
    description: '简陋的木质长剑，聊胜于无。',
    slot: 'WEAPON',
    quality: 'COMMON',
    baseStats: JSON.stringify({ attack: 5 }),
    bonusStats: null,
    maxEnhanceLevel: 5,
    requirements: null,
    sellPrice: 5,
  },
  {
    equipmentId: 'tiejian',
    name: '铁剑',
    description: '普通的铁质长剑，坚固耐用。',
    slot: 'WEAPON',
    quality: 'COMMON',
    baseStats: JSON.stringify({ attack: 12 }),
    bonusStats: null,
    maxEnhanceLevel: 10,
    requirements: null,
    sellPrice: 20,
  },
  {
    equipmentId: 'qingfengjian',
    name: '青锋剑',
    description: '锋利的法剑，剑身泛着青光。',
    slot: 'WEAPON',
    quality: 'UNCOMMON',
    baseStats: JSON.stringify({ attack: 25, speed: 5 }),
    bonusStats: JSON.stringify([{ attribute: 'critRate', value: 3, isPercentage: true }]),
    maxEnhanceLevel: 15,
    requirements: JSON.stringify([{ type: 'realm', value: 'lianqi' }]),
    sellPrice: 100,
  },
  {
    equipmentId: 'hanbing_jian',
    name: '寒冰剑',
    description: '以寒冰精铁铸造，剑身永远覆盖着一层寒霜。',
    slot: 'WEAPON',
    quality: 'RARE',
    baseStats: JSON.stringify({ attack: 45, speed: 8 }),
    bonusStats: JSON.stringify([
      { attribute: 'critRate', value: 5, isPercentage: true },
      { attribute: 'critDamage', value: 10, isPercentage: true },
    ]),
    maxEnhanceLevel: 20,
    requirements: JSON.stringify([{ type: 'realm', value: 'zhuji' }]),
    specialEffect: '攻击有15%概率冰冻敌人1回合',
    sellPrice: 500,
  },
  {
    equipmentId: 'lieyan_jian',
    name: '烈焰剑',
    description: '以天火淬炼的法剑，剑身燃烧着永不熄灭的火焰。',
    slot: 'WEAPON',
    quality: 'RARE',
    baseStats: JSON.stringify({ attack: 50 }),
    bonusStats: JSON.stringify([{ attribute: 'attack', value: 15, isPercentage: true }]),
    maxEnhanceLevel: 20,
    requirements: JSON.stringify([{ type: 'realm', value: 'zhuji' }]),
    specialEffect: '攻击附带20%攻击力的火焰伤害',
    sellPrice: 500,
  },

  // ==================== 武器 - 金丹期 ====================
  {
    equipmentId: 'zixiao_jian',
    name: '紫霄剑',
    description: '传承自上古仙门的法剑，剑身流转着紫色雷霆。',
    slot: 'WEAPON',
    quality: 'EPIC',
    baseStats: JSON.stringify({ attack: 120, speed: 15 }),
    bonusStats: JSON.stringify([
      { attribute: 'critRate', value: 8, isPercentage: true },
      { attribute: 'critDamage', value: 25, isPercentage: true },
    ]),
    maxEnhanceLevel: 30,
    requirements: JSON.stringify([{ type: 'realm', value: 'jindan' }]),
    specialEffect: '暴击时触发雷霆，造成额外50%伤害',
    sellPrice: 3000,
  },
  {
    equipmentId: 'taiyi_jian',
    name: '太乙神剑',
    description: '太乙真人遗留的神兵，蕴含无尽剑意。',
    slot: 'WEAPON',
    quality: 'LEGENDARY',
    baseStats: JSON.stringify({ attack: 250, speed: 25, critRate: 10 }),
    bonusStats: JSON.stringify([
      { attribute: 'attack', value: 20, isPercentage: true },
      { attribute: 'critDamage', value: 50, isPercentage: true },
    ]),
    maxEnhanceLevel: 50,
    requirements: JSON.stringify([{ type: 'realm', value: 'yuanying' }]),
    specialEffect: '剑意加持，所有技能伤害+15%',
    sellPrice: 20000,
  },

  // ==================== 武器 - 顶级 ====================
  {
    equipmentId: 'huntian_jian',
    name: '混天剑',
    description: '开天辟地时诞生的先天至宝，可斩断一切。',
    slot: 'WEAPON',
    quality: 'MYTHIC',
    baseStats: JSON.stringify({ attack: 800, speed: 50, critRate: 15, critDamage: 80 }),
    bonusStats: JSON.stringify([
      { attribute: 'attack', value: 50, isPercentage: true },
      { attribute: 'maxHp', value: 20, isPercentage: true },
    ]),
    maxEnhanceLevel: 100,
    requirements: JSON.stringify([{ type: 'realm', value: 'huashen' }]),
    specialEffect: '无视30%防御，攻击有10%概率造成双倍伤害',
    sellPrice: 200000,
  },

  // ==================== 防具 - 炼气期 ====================
  {
    equipmentId: 'buyi',
    name: '布衣',
    description: '普通的布制衣物，毫无防护力可言。',
    slot: 'ARMOR',
    quality: 'COMMON',
    baseStats: JSON.stringify({ defense: 3 }),
    bonusStats: null,
    maxEnhanceLevel: 5,
    requirements: null,
    sellPrice: 3,
  },
  {
    equipmentId: 'pijiia',
    name: '皮甲',
    description: '兽皮制成的简易护甲。',
    slot: 'ARMOR',
    quality: 'COMMON',
    baseStats: JSON.stringify({ defense: 8, maxHp: 20 }),
    bonusStats: null,
    maxEnhanceLevel: 10,
    requirements: null,
    sellPrice: 15,
  },
  {
    equipmentId: 'lingwen_pao',
    name: '灵纹袍',
    description: '刻有防护灵纹的法袍，是修士的标配。',
    slot: 'ARMOR',
    quality: 'UNCOMMON',
    baseStats: JSON.stringify({ defense: 18, maxHp: 50, maxMp: 20 }),
    bonusStats: null,
    maxEnhanceLevel: 15,
    requirements: JSON.stringify([{ type: 'realm', value: 'lianqi' }]),
    sellPrice: 80,
  },
  {
    equipmentId: 'qingyun_pao',
    name: '青云法袍',
    description: '青云宗弟子专用法袍，防护力强。',
    slot: 'ARMOR',
    quality: 'RARE',
    baseStats: JSON.stringify({ defense: 35, maxHp: 100, maxMp: 50 }),
    bonusStats: JSON.stringify([{ attribute: 'defense', value: 10, isPercentage: true }]),
    maxEnhanceLevel: 20,
    requirements: JSON.stringify([{ type: 'realm', value: 'zhuji' }]),
    sellPrice: 400,
  },

  // ==================== 防具 - 金丹期 ====================
  {
    equipmentId: 'jinling_jia',
    name: '金鳞甲',
    description: '以金鳞蛟皮炼制的法甲，坚韧无比。',
    slot: 'ARMOR',
    quality: 'EPIC',
    baseStats: JSON.stringify({ defense: 80, maxHp: 300, maxMp: 100 }),
    bonusStats: JSON.stringify([
      { attribute: 'defense', value: 15, isPercentage: true },
      { attribute: 'maxHp', value: 10, isPercentage: true },
    ]),
    maxEnhanceLevel: 30,
    requirements: JSON.stringify([{ type: 'realm', value: 'jindan' }]),
    specialEffect: '受到致命伤害时，有20%概率保留1点生命',
    sellPrice: 2500,
  },
  {
    equipmentId: 'xuanwu_jia',
    name: '玄武战甲',
    description: '以玄武真灵精血炼制，防御力冠绝天下。',
    slot: 'ARMOR',
    quality: 'LEGENDARY',
    baseStats: JSON.stringify({ defense: 200, maxHp: 800 }),
    bonusStats: JSON.stringify([
      { attribute: 'defense', value: 30, isPercentage: true },
      { attribute: 'maxHp', value: 25, isPercentage: true },
    ]),
    maxEnhanceLevel: 50,
    requirements: JSON.stringify([{ type: 'realm', value: 'yuanying' }]),
    specialEffect: '每回合恢复5%最大生命值',
    sellPrice: 18000,
  },

  // ==================== 防具 - 顶级 ====================
  {
    equipmentId: 'hundun_pao',
    name: '混沌圣袍',
    description: '混沌之气凝聚而成的圣袍，万法不侵。',
    slot: 'ARMOR',
    quality: 'MYTHIC',
    baseStats: JSON.stringify({ defense: 600, maxHp: 2000, maxMp: 500 }),
    bonusStats: JSON.stringify([
      { attribute: 'defense', value: 50, isPercentage: true },
      { attribute: 'maxHp', value: 40, isPercentage: true },
    ]),
    maxEnhanceLevel: 100,
    requirements: JSON.stringify([{ type: 'realm', value: 'huashen' }]),
    specialEffect: '免疫所有负面状态，受到伤害减少20%',
    sellPrice: 180000,
  },

  // ==================== 饰品 ====================
  {
    equipmentId: 'shouhu_fuzhuan',
    name: '守护符箓',
    description: '简单的护身符，可抵御少量伤害。',
    slot: 'ACCESSORY',
    quality: 'COMMON',
    baseStats: JSON.stringify({ maxHp: 30 }),
    bonusStats: null,
    maxEnhanceLevel: 5,
    requirements: null,
    sellPrice: 10,
  },
  {
    equipmentId: 'lingli_zhuhuan',
    name: '灵力珠环',
    description: '增加灵力的手环，修士常用之物。',
    slot: 'ACCESSORY',
    quality: 'UNCOMMON',
    baseStats: JSON.stringify({ maxMp: 50, attack: 10 }),
    bonusStats: null,
    maxEnhanceLevel: 15,
    requirements: JSON.stringify([{ type: 'realm', value: 'lianqi' }]),
    sellPrice: 60,
  },
  {
    equipmentId: 'yunqi_yupei',
    name: '运气玉佩',
    description: '可提升佩戴者气运的玉佩。',
    slot: 'ACCESSORY',
    quality: 'RARE',
    baseStats: JSON.stringify({}),
    bonusStats: null,
    maxEnhanceLevel: 20,
    requirements: JSON.stringify([{ type: 'realm', value: 'zhuji' }]),
    specialEffect: '气运+10，掉落率+5%',
    sellPrice: 300,
  },
  {
    equipmentId: 'wuxing_lingzhu',
    name: '五行灵珠',
    description: '蕴含五行之力的灵珠，全面提升战斗力。',
    slot: 'ACCESSORY',
    quality: 'EPIC',
    baseStats: JSON.stringify({ attack: 30, defense: 20, speed: 10 }),
    bonusStats: JSON.stringify([
      { attribute: 'attack', value: 10, isPercentage: true },
      { attribute: 'defense', value: 10, isPercentage: true },
    ]),
    maxEnhanceLevel: 30,
    requirements: JSON.stringify([{ type: 'realm', value: 'jindan' }]),
    specialEffect: '五行相生，每种元素技能伤害+10%',
    sellPrice: 2000,
  },
  {
    equipmentId: 'tiandao_zhuhuan',
    name: '天道珠环',
    description: '蕴含天道法则的神秘珠环。',
    slot: 'ACCESSORY',
    quality: 'LEGENDARY',
    baseStats: JSON.stringify({ attack: 80, defense: 50, speed: 30, maxHp: 200, maxMp: 100 }),
    bonusStats: JSON.stringify([
      { attribute: 'attack', value: 15, isPercentage: true },
      { attribute: 'critRate', value: 10, isPercentage: true },
    ]),
    maxEnhanceLevel: 50,
    requirements: JSON.stringify([{ type: 'realm', value: 'yuanying' }]),
    specialEffect: '感悟天道，悟性+15，突破成功率+10%',
    sellPrice: 15000,
  },
  {
    equipmentId: 'hundun_zhuhuan',
    name: '混沌珠环',
    description: '混沌之力凝聚的至宝，无尽玄妙。',
    slot: 'ACCESSORY',
    quality: 'MYTHIC',
    baseStats: JSON.stringify({ attack: 200, defense: 150, speed: 80, maxHp: 500, maxMp: 300 }),
    bonusStats: JSON.stringify([
      { attribute: 'attack', value: 30, isPercentage: true },
      { attribute: 'defense', value: 30, isPercentage: true },
      { attribute: 'critDamage', value: 50, isPercentage: true },
    ]),
    maxEnhanceLevel: 100,
    requirements: JSON.stringify([{ type: 'realm', value: 'huashen' }]),
    specialEffect: '混沌护体，战斗中所有属性+20%',
    sellPrice: 150000,
  },

  // ==================== 头盔 ====================
  {
    equipmentId: 'putong_toukui',
    name: '普通头盔',
    description: '简单的皮质头盔。',
    slot: 'HELMET',
    quality: 'COMMON',
    baseStats: JSON.stringify({ defense: 3, maxHp: 10 }),
    bonusStats: null,
    maxEnhanceLevel: 5,
    requirements: null,
    sellPrice: 8,
  },
  {
    equipmentId: 'lingwen_guan',
    name: '灵纹冠',
    description: '刻有灵纹的法冠，提供基础防护。',
    slot: 'HELMET',
    quality: 'UNCOMMON',
    baseStats: JSON.stringify({ defense: 10, maxHp: 30, maxMp: 15 }),
    bonusStats: null,
    maxEnhanceLevel: 15,
    requirements: JSON.stringify([{ type: 'realm', value: 'lianqi' }]),
    sellPrice: 50,
  },
  {
    equipmentId: 'zijin_guan',
    name: '紫金冠',
    description: '以紫金打造的华贵法冠。',
    slot: 'HELMET',
    quality: 'RARE',
    baseStats: JSON.stringify({ defense: 25, maxHp: 80, maxMp: 40 }),
    bonusStats: JSON.stringify([{ attribute: 'maxMp', value: 10, isPercentage: true }]),
    maxEnhanceLevel: 20,
    requirements: JSON.stringify([{ type: 'realm', value: 'zhuji' }]),
    sellPrice: 250,
  },

  // ==================== 靴子 ====================
  {
    equipmentId: 'buzu_xie',
    name: '布足鞋',
    description: '普通的布鞋。',
    slot: 'BOOTS',
    quality: 'COMMON',
    baseStats: JSON.stringify({ speed: 3 }),
    bonusStats: null,
    maxEnhanceLevel: 5,
    requirements: null,
    sellPrice: 5,
  },
  {
    equipmentId: 'qingfeng_xue',
    name: '清风靴',
    description: '穿上后身轻如燕。',
    slot: 'BOOTS',
    quality: 'UNCOMMON',
    baseStats: JSON.stringify({ speed: 10, defense: 5 }),
    bonusStats: null,
    maxEnhanceLevel: 15,
    requirements: JSON.stringify([{ type: 'realm', value: 'lianqi' }]),
    sellPrice: 45,
  },
  {
    equipmentId: 'lingyun_xue',
    name: '凌云靴',
    description: '踏云而行，速度极快。',
    slot: 'BOOTS',
    quality: 'RARE',
    baseStats: JSON.stringify({ speed: 25, defense: 15 }),
    bonusStats: JSON.stringify([{ attribute: 'speed', value: 10, isPercentage: true }]),
    maxEnhanceLevel: 20,
    requirements: JSON.stringify([{ type: 'realm', value: 'zhuji' }]),
    specialEffect: '战斗中先手概率+15%',
    sellPrice: 220,
  },

  // ==================== 符箓 ====================
  {
    equipmentId: 'huoyan_fu',
    name: '火焰符',
    description: '蕴含火焰之力的符箓。',
    slot: 'TALISMAN',
    quality: 'UNCOMMON',
    baseStats: JSON.stringify({ attack: 15 }),
    bonusStats: null,
    maxEnhanceLevel: 15,
    requirements: JSON.stringify([{ type: 'realm', value: 'lianqi' }]),
    specialEffect: '攻击附带5%火焰伤害',
    sellPrice: 40,
  },
  {
    equipmentId: 'bingfeng_fu',
    name: '冰封符',
    description: '蕴含寒冰之力的符箓。',
    slot: 'TALISMAN',
    quality: 'UNCOMMON',
    baseStats: JSON.stringify({ attack: 12, defense: 8 }),
    bonusStats: null,
    maxEnhanceLevel: 15,
    requirements: JSON.stringify([{ type: 'realm', value: 'lianqi' }]),
    specialEffect: '攻击有5%概率减速敌人',
    sellPrice: 40,
  },
  {
    equipmentId: 'leiting_fu',
    name: '雷霆符',
    description: '蕴含雷霆之力的符箓。',
    slot: 'TALISMAN',
    quality: 'RARE',
    baseStats: JSON.stringify({ attack: 30, speed: 10 }),
    bonusStats: JSON.stringify([{ attribute: 'critRate', value: 5, isPercentage: true }]),
    maxEnhanceLevel: 20,
    requirements: JSON.stringify([{ type: 'realm', value: 'zhuji' }]),
    specialEffect: '暴击时触发雷击，造成额外20%伤害',
    sellPrice: 200,
  },
];
