// 物品模板种子数据

export const itemTemplatesData = [
  // ==================== 消耗品 - 回复类 ====================
  {
    itemId: 'xiaohuandan',
    name: '小还丹',
    description: '最基础的疗伤丹药，可恢复少量生命值。',
    type: 'CONSUMABLE',
    quality: 'COMMON',
    stackable: true,
    maxStack: 99,
    effects: JSON.stringify([{ type: 'heal_hp', value: 50 }]),
    sellPrice: 5,
    buyPrice: 10,
  },
  {
    itemId: 'huiqidan',
    name: '回气丹',
    description: '恢复法力的丹药，修士常备之物。',
    type: 'CONSUMABLE',
    quality: 'COMMON',
    stackable: true,
    maxStack: 99,
    effects: JSON.stringify([{ type: 'heal_mp', value: 30 }]),
    sellPrice: 5,
    buyPrice: 10,
  },
  {
    itemId: 'yangshengdan',
    name: '养生丹',
    description: '温养身体的丹药，可恢复生命和法力。',
    type: 'CONSUMABLE',
    quality: 'UNCOMMON',
    stackable: true,
    maxStack: 99,
    effects: JSON.stringify([
      { type: 'heal_hp', value: 100 },
      { type: 'heal_mp', value: 50 },
    ]),
    sellPrice: 20,
    buyPrice: 50,
  },
  {
    itemId: 'dahuandan',
    name: '大还丹',
    description: '高品质疗伤丹药，可恢复大量生命值。',
    type: 'CONSUMABLE',
    quality: 'RARE',
    stackable: true,
    maxStack: 99,
    effects: JSON.stringify([{ type: 'heal_hp', value: 300 }]),
    sellPrice: 100,
    buyPrice: 250,
  },
  {
    itemId: 'jiuxiansan',
    name: '九仙散',
    description: '传说中的仙丹，可完全恢复生命和法力。',
    type: 'CONSUMABLE',
    quality: 'EPIC',
    stackable: true,
    maxStack: 10,
    effects: JSON.stringify([
      { type: 'heal_hp_percent', value: 100 },
      { type: 'heal_mp_percent', value: 100 },
    ]),
    sellPrice: 1000,
    buyPrice: 5000,
  },

  // ==================== 消耗品 - 修为类 ====================
  {
    itemId: 'juyuandan',
    name: '聚元丹',
    description: '凝聚天地精华的丹药，可增加100点修为。',
    type: 'CONSUMABLE',
    quality: 'UNCOMMON',
    stackable: true,
    maxStack: 99,
    effects: JSON.stringify([{ type: 'add_cultivation', value: 100 }]),
    sellPrice: 30,
    buyPrice: 80,
  },
  {
    itemId: 'xisuilingye',
    name: '洗髓灵液',
    description: '洗涤筋骨髓脉，永久提升少量悟性。',
    type: 'CONSUMABLE',
    quality: 'RARE',
    stackable: true,
    maxStack: 10,
    effects: JSON.stringify([{ type: 'permanent_comprehension', value: 1 }]),
    sellPrice: 500,
    buyPrice: 2000,
  },
  {
    itemId: 'zhujiwan',
    name: '筑基丸',
    description: '筑基期专用丹药，提升20%突破成功率。',
    type: 'CONSUMABLE',
    quality: 'RARE',
    stackable: true,
    maxStack: 5,
    effects: JSON.stringify([{ type: 'breakthrough_bonus', value: 20, duration: 1 }]),
    sellPrice: 200,
    buyPrice: 800,
  },
  {
    itemId: 'pojiaodan',
    name: '破境丹',
    description: '突破瓶颈的珍贵丹药，提升30%突破成功率。',
    type: 'CONSUMABLE',
    quality: 'EPIC',
    stackable: true,
    maxStack: 10,
    effects: JSON.stringify([{ type: 'breakthrough_bonus', value: 30, duration: 1 }]),
    sellPrice: 800,
    buyPrice: 3000,
  },
  {
    itemId: 'jindanluyao',
    name: '金丹炉要',
    description: '结丹期必备丹药，大幅提升结丹成功率。',
    type: 'CONSUMABLE',
    quality: 'EPIC',
    stackable: true,
    maxStack: 3,
    effects: JSON.stringify([{ type: 'breakthrough_bonus', value: 40, duration: 1 }]),
    sellPrice: 2000,
    buyPrice: 10000,
  },

  // ==================== 消耗品 - 战斗增益 ====================
  {
    itemId: 'liliwan',
    name: '力力丸',
    description: '短时间内大幅提升攻击力。',
    type: 'CONSUMABLE',
    quality: 'UNCOMMON',
    stackable: true,
    maxStack: 20,
    effects: JSON.stringify([{ type: 'buff_attack', value: 50, duration: 60 }]),
    sellPrice: 15,
    buyPrice: 40,
  },
  {
    itemId: 'tiepidan',
    name: '铁皮丹',
    description: '短时间内大幅提升防御力。',
    type: 'CONSUMABLE',
    quality: 'UNCOMMON',
    stackable: true,
    maxStack: 20,
    effects: JSON.stringify([{ type: 'buff_defense', value: 50, duration: 60 }]),
    sellPrice: 15,
    buyPrice: 40,
  },
  {
    itemId: 'shenfengsan',
    name: '神风散',
    description: '短时间内大幅提升速度。',
    type: 'CONSUMABLE',
    quality: 'UNCOMMON',
    stackable: true,
    maxStack: 20,
    effects: JSON.stringify([{ type: 'buff_speed', value: 30, duration: 60 }]),
    sellPrice: 15,
    buyPrice: 40,
  },

  // ==================== 消耗品 - 特殊 ====================
  {
    itemId: 'xumingdan',
    name: '续命丹',
    description: '延长寿元的珍贵丹药，增加50年寿元。',
    type: 'CONSUMABLE',
    quality: 'LEGENDARY',
    stackable: true,
    maxStack: 5,
    effects: JSON.stringify([{ type: 'add_lifespan', value: 50 }]),
    sellPrice: 5000,
    buyPrice: 50000,
  },
  {
    itemId: 'hunyuandan',
    name: '混元丹',
    description: '传说中的仙丹，可提升灵根纯度5%。',
    type: 'CONSUMABLE',
    quality: 'MYTHIC',
    stackable: false,
    maxStack: 1,
    effects: JSON.stringify([{ type: 'improve_spiritual_root', value: 5 }]),
    sellPrice: 50000,
    buyPrice: null,
  },

  // ==================== 货币 ====================
  {
    itemId: 'lingshi',
    name: '灵石',
    description: '修仙界通用货币，蕴含微量灵气。',
    type: 'CURRENCY',
    quality: 'COMMON',
    stackable: true,
    maxStack: 999999,
    effects: null,
    sellPrice: 1,
    buyPrice: null,
  },
  {
    itemId: 'zhongpinlingshi',
    name: '中品灵石',
    description: '品质较高的灵石，等同于100枚下品灵石。',
    type: 'CURRENCY',
    quality: 'UNCOMMON',
    stackable: true,
    maxStack: 99999,
    effects: null,
    sellPrice: 100,
    buyPrice: null,
  },
  {
    itemId: 'shangpinlingshi',
    name: '上品灵石',
    description: '高品质灵石，等同于100枚中品灵石。',
    type: 'CURRENCY',
    quality: 'RARE',
    stackable: true,
    maxStack: 9999,
    effects: null,
    sellPrice: 10000,
    buyPrice: null,
  },

  // ==================== 材料 - 炼丹 ====================
  {
    itemId: 'lingcao',
    name: '灵草',
    description: '最常见的炼丹材料，生长于灵气充裕之地。',
    type: 'MATERIAL',
    quality: 'COMMON',
    stackable: true,
    maxStack: 999,
    effects: null,
    sellPrice: 2,
    buyPrice: 5,
  },
  {
    itemId: 'bainianlingshen',
    name: '百年灵参',
    description: '生长百年的灵参，炼丹主药。',
    type: 'MATERIAL',
    quality: 'UNCOMMON',
    stackable: true,
    maxStack: 99,
    effects: null,
    sellPrice: 50,
    buyPrice: 150,
  },
  {
    itemId: 'qiannianxuezhi',
    name: '千年雪芝',
    description: '极寒之地生长的珍贵灵芝。',
    type: 'MATERIAL',
    quality: 'RARE',
    stackable: true,
    maxStack: 50,
    effects: null,
    sellPrice: 300,
    buyPrice: 1000,
  },
  {
    itemId: 'wannianheshouyang',
    name: '万年何首乌',
    description: '传说中的仙草，可增长寿元。',
    type: 'MATERIAL',
    quality: 'EPIC',
    stackable: true,
    maxStack: 10,
    effects: null,
    sellPrice: 2000,
    buyPrice: 8000,
  },
  {
    itemId: 'jiupinlingzhi',
    name: '九品灵芝',
    description: '灵芝中的极品，通体呈紫金色。',
    type: 'MATERIAL',
    quality: 'LEGENDARY',
    stackable: true,
    maxStack: 5,
    effects: null,
    sellPrice: 10000,
    buyPrice: null,
  },

  // ==================== 材料 - 炼器 ====================
  {
    itemId: 'xuantie',
    name: '玄铁',
    description: '炼器常用材料，坚硬异常。',
    type: 'MATERIAL',
    quality: 'COMMON',
    stackable: true,
    maxStack: 999,
    effects: null,
    sellPrice: 5,
    buyPrice: 15,
  },
  {
    itemId: 'hanbing',
    name: '寒冰精铁',
    description: '寒冰矿脉中提炼的金属，自带冰寒属性。',
    type: 'MATERIAL',
    quality: 'UNCOMMON',
    stackable: true,
    maxStack: 99,
    effects: null,
    sellPrice: 80,
    buyPrice: 200,
  },
  {
    itemId: 'leiyin',
    name: '雷印银',
    description: '遭受天雷淬炼的银矿，蕴含雷霆之力。',
    type: 'MATERIAL',
    quality: 'RARE',
    stackable: true,
    maxStack: 50,
    effects: null,
    sellPrice: 500,
    buyPrice: 1500,
  },
  {
    itemId: 'tianyuanjin',
    name: '天元金',
    description: '天外陨石中提炼的稀有金属。',
    type: 'MATERIAL',
    quality: 'EPIC',
    stackable: true,
    maxStack: 20,
    effects: null,
    sellPrice: 3000,
    buyPrice: 12000,
  },
  {
    itemId: 'huntunjing',
    name: '混沌精铁',
    description: '传说中开天辟地时遗留的神秘金属。',
    type: 'MATERIAL',
    quality: 'LEGENDARY',
    stackable: true,
    maxStack: 5,
    effects: null,
    sellPrice: 20000,
    buyPrice: null,
  },

  // ==================== 材料 - 妖兽 ====================
  {
    itemId: 'langya',
    name: '灵狼牙',
    description: '灵狼的獠牙，可炼制武器。',
    type: 'MATERIAL',
    quality: 'COMMON',
    stackable: true,
    maxStack: 99,
    effects: null,
    sellPrice: 8,
    buyPrice: 20,
  },
  {
    itemId: 'hupi',
    name: '虎皮',
    description: '灵虎的皮革，可炼制防具。',
    type: 'MATERIAL',
    quality: 'UNCOMMON',
    stackable: true,
    maxStack: 50,
    effects: null,
    sellPrice: 60,
    buyPrice: 180,
  },
  {
    itemId: 'yaoshouneidan',
    name: '妖兽内丹',
    description: '妖兽的内丹，蕴含强大妖力。',
    type: 'MATERIAL',
    quality: 'RARE',
    stackable: true,
    maxStack: 20,
    effects: null,
    sellPrice: 400,
    buyPrice: 1200,
  },
  {
    itemId: 'jiaolongjin',
    name: '蛟龙筋',
    description: '蛟龙的筋脉，炼器上品材料。',
    type: 'MATERIAL',
    quality: 'EPIC',
    stackable: true,
    maxStack: 10,
    effects: null,
    sellPrice: 2500,
    buyPrice: 10000,
  },
  {
    itemId: 'zhenlongxue',
    name: '真龙血',
    description: '真龙的精血，天地至宝。',
    type: 'MATERIAL',
    quality: 'MYTHIC',
    stackable: true,
    maxStack: 3,
    effects: null,
    sellPrice: 100000,
    buyPrice: null,
  },

  // ==================== 任务物品 ====================
  {
    itemId: 'taichuyinqijue',
    name: '太初引气诀',
    description: '山洞中发现的古老功法，记载着引气入体的法门。',
    type: 'QUEST',
    quality: 'RARE',
    stackable: false,
    maxStack: 1,
    effects: null,
    sellPrice: 0,
    buyPrice: null,
  },
  {
    itemId: 'qingyunlingpai',
    name: '青云令牌',
    description: '青云宗的入门令牌，凭此可参加入门考核。',
    type: 'QUEST',
    quality: 'UNCOMMON',
    stackable: false,
    maxStack: 1,
    effects: null,
    sellPrice: 0,
    buyPrice: null,
  },
  {
    itemId: 'miwuzhishui',
    name: '迷雾之水',
    description: '迷雾林深处的泉水，据说有奇效。',
    type: 'QUEST',
    quality: 'RARE',
    stackable: true,
    maxStack: 5,
    effects: null,
    sellPrice: 0,
    buyPrice: null,
  },
  {
    itemId: 'shizongdizibiji',
    name: '失踪弟子笔记',
    description: '失踪弟子留下的笔记，记录着可怕的发现。',
    type: 'QUEST',
    quality: 'RARE',
    stackable: false,
    maxStack: 1,
    effects: null,
    sellPrice: 0,
    buyPrice: null,
  },
  {
    itemId: 'moqiyuanshi',
    name: '魔气源石',
    description: '散发着浓郁魔气的黑色石头。',
    type: 'QUEST',
    quality: 'EPIC',
    stackable: false,
    maxStack: 1,
    effects: null,
    sellPrice: 0,
    buyPrice: null,
  },
  {
    itemId: 'jindanyaoyin',
    name: '金丹药引',
    description: '结丹必备的药引，极其珍贵。',
    type: 'QUEST',
    quality: 'EPIC',
    stackable: false,
    maxStack: 1,
    effects: null,
    sellPrice: 0,
    buyPrice: null,
  },
  {
    itemId: 'wuxinglingshi',
    name: '五行灵石',
    description: '蕴含五行之力的神秘灵石。',
    type: 'QUEST',
    quality: 'LEGENDARY',
    stackable: false,
    maxStack: 1,
    effects: null,
    sellPrice: 0,
    buyPrice: null,
  },
  {
    itemId: 'yuanyingleiguo',
    name: '元婴雷果',
    description: '突破元婴期必需的天材地宝。',
    type: 'QUEST',
    quality: 'LEGENDARY',
    stackable: false,
    maxStack: 1,
    effects: null,
    sellPrice: 0,
    buyPrice: null,
  },
  {
    itemId: 'feishenglingshi',
    name: '飞升灵石',
    description: '蕴含飞升之力的神秘灵石。',
    type: 'QUEST',
    quality: 'MYTHIC',
    stackable: false,
    maxStack: 1,
    effects: null,
    sellPrice: 0,
    buyPrice: null,
  },
];
