// 出身和灵根配置种子数据
// 从前端 src/data/origins.ts 迁移

export const originConfigsData = [
  {
    originId: 'village_orphan',
    name: '山村孤儿',
    description: '自幼父母双亡，在山村中长大，偶然获得修仙功法',
    bonuses: JSON.stringify({ comprehension: 2, luck: 3 }),
    startItems: JSON.stringify([{ itemId: 'healing_pill_small', quantity: 5 }]),
    startStoryId: 'prologue',
  },
  {
    originId: 'fallen_clan',
    name: '没落世家',
    description: '出身修仙世家，但家族已没落，身怀家传功法',
    bonuses: JSON.stringify({ attack: 3, defense: 2 }),
    startItems: JSON.stringify([{ itemId: 'healing_pill_small', quantity: 3 }, { itemId: 'spirit_stone', quantity: 50 }]),
    startStoryId: 'prologue',
  },
  {
    originId: 'reincarnation',
    name: '转世重修',
    description: '前世为强大修士，转世后记忆渐渐觉醒',
    bonuses: JSON.stringify({ comprehension: 5 }),
    startItems: JSON.stringify([{ itemId: 'healing_pill_small', quantity: 3 }]),
    startStoryId: 'prologue',
  },
];

export const spiritRootConfigsData = [
  {
    rootId: 'metal_single',
    name: '金灵根',
    description: '纯粹的金属性灵根，攻击力加成',
    quality: 'heavenly',
    elements: JSON.stringify(['metal']),
    bonuses: JSON.stringify({ attack: 10, critRate: 0.05 }),
    cultivationBonus: 1.5,
  },
  {
    rootId: 'wood_single',
    name: '木灵根',
    description: '纯粹的木属性灵根，恢复力加成',
    quality: 'heavenly',
    elements: JSON.stringify(['wood']),
    bonuses: JSON.stringify({ maxHp: 50, defense: 5 }),
    cultivationBonus: 1.5,
  },
  {
    rootId: 'water_single',
    name: '水灵根',
    description: '纯粹的水属性灵根，速度加成',
    quality: 'heavenly',
    elements: JSON.stringify(['water']),
    bonuses: JSON.stringify({ speed: 10, defense: 3 }),
    cultivationBonus: 1.5,
  },
  {
    rootId: 'fire_single',
    name: '火灵根',
    description: '纯粹的火属性灵根，高攻击加成',
    quality: 'heavenly',
    elements: JSON.stringify(['fire']),
    bonuses: JSON.stringify({ attack: 12, critDamage: 0.2 }),
    cultivationBonus: 1.5,
  },
  {
    rootId: 'earth_single',
    name: '土灵根',
    description: '纯粹的土属性灵根，防御加成',
    quality: 'heavenly',
    elements: JSON.stringify(['earth']),
    bonuses: JSON.stringify({ defense: 10, maxHp: 30 }),
    cultivationBonus: 1.5,
  },
  {
    rootId: 'dual_metal_fire',
    name: '金火双灵根',
    description: '金火双属性灵根',
    quality: 'excellent',
    elements: JSON.stringify(['metal', 'fire']),
    bonuses: JSON.stringify({ attack: 7, critRate: 0.03 }),
    cultivationBonus: 1.3,
  },
  {
    rootId: 'dual_wood_water',
    name: '木水双灵根',
    description: '木水双属性灵根',
    quality: 'excellent',
    elements: JSON.stringify(['wood', 'water']),
    bonuses: JSON.stringify({ maxHp: 30, speed: 5 }),
    cultivationBonus: 1.3,
  },
  {
    rootId: 'triple_common',
    name: '三灵根',
    description: '三种属性灵根',
    quality: 'ordinary',
    elements: JSON.stringify(['metal', 'wood', 'water']),
    bonuses: JSON.stringify({ attack: 3, defense: 3, speed: 3 }),
    cultivationBonus: 1.0,
  },
  {
    rootId: 'penta_common',
    name: '五灵根',
    description: '五种属性灵根，修炼速度较慢',
    quality: 'ordinary',
    elements: JSON.stringify(['metal', 'wood', 'water', 'fire', 'earth']),
    bonuses: JSON.stringify({ attack: 1, defense: 1, speed: 1, maxHp: 10 }),
    cultivationBonus: 0.8,
  },
];
