// 境界配置种子数据
// 从前端 src/data/realms/index.ts 迁移

export const realmConfigsData = [
  {
    realmId: 'lianqi',
    name: 'lianqi',
    displayName: '炼气',
    order: 0,
    stages: JSON.stringify([
      { stage: 'early', displayName: '炼气初期', cultivationNeeded: 100 },
      { stage: 'middle', displayName: '炼气中期', cultivationNeeded: 300 },
      { stage: 'late', displayName: '炼气后期', cultivationNeeded: 600 },
      { stage: 'peak', displayName: '炼气圆满', cultivationNeeded: 1000 },
    ]),
    breakthroughConditions: null,
    attributeBonuses: null,
  },
  {
    realmId: 'zhuji',
    name: 'zhuji',
    displayName: '筑基',
    order: 1,
    stages: JSON.stringify([
      { stage: 'early', displayName: '筑基初期', cultivationNeeded: 2000 },
      { stage: 'middle', displayName: '筑基中期', cultivationNeeded: 5000 },
      { stage: 'late', displayName: '筑基后期', cultivationNeeded: 10000 },
      { stage: 'peak', displayName: '筑基圆满', cultivationNeeded: 18000 },
    ]),
    breakthroughConditions: JSON.stringify({ minLevel: 4 }),
    attributeBonuses: JSON.stringify({ attack: 5, defense: 3, speed: 2, maxHp: 50 }),
  },
  {
    realmId: 'jindan',
    name: 'jindan',
    displayName: '金丹',
    order: 2,
    stages: JSON.stringify([
      { stage: 'early', displayName: '金丹初期', cultivationNeeded: 30000 },
      { stage: 'middle', displayName: '金丹中期', cultivationNeeded: 60000 },
      { stage: 'late', displayName: '金丹后期', cultivationNeeded: 100000 },
      { stage: 'peak', displayName: '金丹圆满', cultivationNeeded: 160000 },
    ]),
    breakthroughConditions: JSON.stringify({ minLevel: 8 }),
    attributeBonuses: JSON.stringify({ attack: 15, defense: 10, speed: 5, maxHp: 200 }),
  },
  {
    realmId: 'yuanying',
    name: 'yuanying',
    displayName: '元婴',
    order: 3,
    stages: JSON.stringify([
      { stage: 'early', displayName: '元婴初期', cultivationNeeded: 250000 },
      { stage: 'middle', displayName: '元婴中期', cultivationNeeded: 500000 },
      { stage: 'late', displayName: '元婴后期', cultivationNeeded: 800000 },
      { stage: 'peak', displayName: '元婴圆满', cultivationNeeded: 1200000 },
    ]),
    breakthroughConditions: JSON.stringify({ minLevel: 12 }),
    attributeBonuses: JSON.stringify({ attack: 40, defense: 30, speed: 15, maxHp: 600 }),
  },
  {
    realmId: 'huashen',
    name: 'huashen',
    displayName: '化神',
    order: 4,
    stages: JSON.stringify([
      { stage: 'early', displayName: '化神初期', cultivationNeeded: 2000000 },
      { stage: 'middle', displayName: '化神中期', cultivationNeeded: 4000000 },
      { stage: 'late', displayName: '化神后期', cultivationNeeded: 7000000 },
      { stage: 'peak', displayName: '化神圆满', cultivationNeeded: 12000000 },
    ]),
    breakthroughConditions: JSON.stringify({ minLevel: 16 }),
    attributeBonuses: JSON.stringify({ attack: 100, defense: 80, speed: 40, maxHp: 2000 }),
  },
  {
    realmId: 'heti',
    name: 'heti',
    displayName: '合体',
    order: 5,
    stages: JSON.stringify([
      { stage: 'early', displayName: '合体初期', cultivationNeeded: 20000000 },
      { stage: 'middle', displayName: '合体中期', cultivationNeeded: 40000000 },
      { stage: 'late', displayName: '合体后期', cultivationNeeded: 70000000 },
      { stage: 'peak', displayName: '合体圆满', cultivationNeeded: 120000000 },
    ]),
    breakthroughConditions: JSON.stringify({ minLevel: 20 }),
    attributeBonuses: JSON.stringify({ attack: 300, defense: 250, speed: 100, maxHp: 6000 }),
  },
  {
    realmId: 'dacheng',
    name: 'dacheng',
    displayName: '大乘',
    order: 6,
    stages: JSON.stringify([
      { stage: 'early', displayName: '大乘初期', cultivationNeeded: 200000000 },
      { stage: 'middle', displayName: '大乘中期', cultivationNeeded: 400000000 },
      { stage: 'late', displayName: '大乘后期', cultivationNeeded: 700000000 },
      { stage: 'peak', displayName: '大乘圆满', cultivationNeeded: 1200000000 },
    ]),
    breakthroughConditions: JSON.stringify({ minLevel: 24 }),
    attributeBonuses: JSON.stringify({ attack: 800, defense: 600, speed: 300, maxHp: 20000 }),
  },
  {
    realmId: 'dujie',
    name: 'dujie',
    displayName: '渡劫',
    order: 7,
    stages: JSON.stringify([
      { stage: 'early', displayName: '渡劫初期', cultivationNeeded: 2000000000 },
      { stage: 'middle', displayName: '渡劫中期', cultivationNeeded: 5000000000 },
      { stage: 'late', displayName: '渡劫后期', cultivationNeeded: 10000000000 },
      { stage: 'peak', displayName: '渡劫圆满', cultivationNeeded: 20000000000 },
    ]),
    breakthroughConditions: JSON.stringify({ minLevel: 28 }),
    attributeBonuses: JSON.stringify({ attack: 2000, defense: 1500, speed: 800, maxHp: 60000 }),
  },
  {
    realmId: 'xianren',
    name: 'xianren',
    displayName: '仙人',
    order: 8,
    stages: JSON.stringify([
      { stage: 'early', displayName: '仙人初期', cultivationNeeded: 50000000000 },
      { stage: 'middle', displayName: '仙人中期', cultivationNeeded: 100000000000 },
      { stage: 'late', displayName: '仙人后期', cultivationNeeded: 200000000000 },
      { stage: 'peak', displayName: '仙人圆满', cultivationNeeded: 500000000000 },
    ]),
    breakthroughConditions: JSON.stringify({ minLevel: 32 }),
    attributeBonuses: JSON.stringify({ attack: 5000, defense: 4000, speed: 2000, maxHp: 200000 }),
  },
];
