// 炼丹系统种子数据
// 从前端 src/data/alchemy/index.ts 迁移

export const alchemyRecipesData = [
  {
    recipeId: 'qi_gathering_pill',
    name: '聚气丹',
    description: '凝聚天地灵气，加速修炼',
    level: 1,
    difficulty: 1.0,
    materials: JSON.stringify([{ itemId: 'spirit_grass', quantity: 3 }, { itemId: 'morning_dew', quantity: 2 }]),
    resultItemId: 'qi_gathering_pill',
    resultQuantity: 3,
    baseSuccessRate: 0.8,
    requiredCauldronLevel: 1,
  },
  {
    recipeId: 'healing_pill',
    name: '疗伤丹',
    description: '治愈伤势，恢复气血',
    level: 1,
    difficulty: 1.0,
    materials: JSON.stringify([{ itemId: 'blood_ginseng', quantity: 2 }, { itemId: 'spirit_grass', quantity: 2 }]),
    resultItemId: 'healing_pill',
    resultQuantity: 5,
    baseSuccessRate: 0.85,
    requiredCauldronLevel: 1,
  },
  {
    recipeId: 'spirit_recovery_pill',
    name: '回灵丹',
    description: '恢复法力',
    level: 2,
    difficulty: 1.2,
    materials: JSON.stringify([{ itemId: 'blue_lotus', quantity: 2 }, { itemId: 'spirit_water', quantity: 1 }]),
    resultItemId: 'spirit_recovery_pill',
    resultQuantity: 4,
    baseSuccessRate: 0.8,
    requiredCauldronLevel: 1,
  },
  {
    recipeId: 'foundation_pill',
    name: '筑基丹',
    description: '稳固根基，突破必备',
    level: 5,
    difficulty: 2.0,
    materials: JSON.stringify([{ itemId: 'earth_essence', quantity: 3 }, { itemId: 'century_ginseng', quantity: 1 }, { itemId: 'spirit_stone', quantity: 10 }]),
    resultItemId: 'foundation_pill',
    resultQuantity: 1,
    baseSuccessRate: 0.5,
    requiredCauldronLevel: 2,
  },
  {
    recipeId: 'power_pill',
    name: '蛮力丹',
    description: '临时大幅提升攻击力',
    level: 4,
    difficulty: 1.5,
    materials: JSON.stringify([{ itemId: 'fire_essence', quantity: 2 }, { itemId: 'tiger_bone', quantity: 1 }, { itemId: 'beast_blood', quantity: 3 }]),
    resultItemId: 'power_pill',
    resultQuantity: 2,
    baseSuccessRate: 0.6,
    requiredCauldronLevel: 2,
  },
  {
    recipeId: 'golden_core_pill',
    name: '金丹',
    description: '凝结金丹的辅助圣药',
    level: 10,
    difficulty: 3.0,
    materials: JSON.stringify([{ itemId: 'golden_essence', quantity: 5 }, { itemId: 'thousand_year_ginseng', quantity: 1 }, { itemId: 'dragon_blood', quantity: 1 }, { itemId: 'high_spirit_stone', quantity: 5 }]),
    resultItemId: 'golden_core_pill',
    resultQuantity: 1,
    baseSuccessRate: 0.3,
    requiredCauldronLevel: 4,
  },
  {
    recipeId: 'longevity_pill',
    name: '驻颜丹',
    description: '延长寿元',
    level: 12,
    difficulty: 3.5,
    materials: JSON.stringify([{ itemId: 'life_fruit', quantity: 1 }, { itemId: 'thousand_year_ginseng', quantity: 2 }, { itemId: 'phoenix_feather', quantity: 1 }]),
    resultItemId: 'longevity_pill',
    resultQuantity: 1,
    baseSuccessRate: 0.2,
    requiredCauldronLevel: 5,
  },
  {
    recipeId: 'root_cleansing_pill',
    name: '洗髓丹',
    description: '净化灵根，提升资质',
    level: 20,
    difficulty: 5.0,
    materials: JSON.stringify([{ itemId: 'chaos_essence', quantity: 1 }, { itemId: 'nine_leaf_clover', quantity: 1 }, { itemId: 'immortal_spring_water', quantity: 1 }, { itemId: 'supreme_spirit_stone', quantity: 10 }]),
    resultItemId: 'root_cleansing_pill',
    resultQuantity: 1,
    baseSuccessRate: 0.1,
    requiredCauldronLevel: 7,
  },
  {
    recipeId: 'jindan_recovery_pill',
    name: '金丹恢复丹',
    description: '金丹期修士专用的恢复丹药',
    level: 6,
    difficulty: 1.8,
    materials: JSON.stringify([{ itemId: 'blood_ginseng', quantity: 3 }, { itemId: 'golden_essence', quantity: 1 }, { itemId: 'spirit_grass', quantity: 5 }]),
    resultItemId: 'jindan_recovery_pill',
    resultQuantity: 3,
    baseSuccessRate: 0.6,
    requiredCauldronLevel: 3,
  },
  {
    recipeId: 'yuanying_recovery_pill',
    name: '元婴恢复丹',
    description: '元婴期修士专用的恢复丹药',
    level: 10,
    difficulty: 2.5,
    materials: JSON.stringify([{ itemId: 'thousand_year_ginseng', quantity: 1 }, { itemId: 'blood_ginseng', quantity: 5 }, { itemId: 'spirit_water', quantity: 3 }]),
    resultItemId: 'yuanying_recovery_pill',
    resultQuantity: 2,
    baseSuccessRate: 0.4,
    requiredCauldronLevel: 4,
  },
  {
    recipeId: 'huashen_recovery_pill',
    name: '化神恢复丹',
    description: '化神期修士专用的恢复丹药',
    level: 14,
    difficulty: 3.0,
    materials: JSON.stringify([{ itemId: 'thousand_year_ginseng', quantity: 2 }, { itemId: 'life_fruit', quantity: 1 }, { itemId: 'earth_essence', quantity: 3 }]),
    resultItemId: 'huashen_recovery_pill',
    resultQuantity: 2,
    baseSuccessRate: 0.3,
    requiredCauldronLevel: 5,
  },
  {
    recipeId: 'yuanying_breakthrough_pill',
    name: '元婴丹',
    description: '辅助元婴突破的珍贵丹药',
    level: 12,
    difficulty: 3.0,
    materials: JSON.stringify([{ itemId: 'golden_essence', quantity: 3 }, { itemId: 'dragon_blood', quantity: 1 }, { itemId: 'thousand_year_ginseng', quantity: 2 }]),
    resultItemId: 'yuanying_breakthrough_pill',
    resultQuantity: 1,
    baseSuccessRate: 0.25,
    requiredCauldronLevel: 5,
  },
  {
    recipeId: 'huashen_breakthrough_pill',
    name: '化神丹',
    description: '辅助化神期突破的极品丹药',
    level: 16,
    difficulty: 4.0,
    materials: JSON.stringify([{ itemId: 'phoenix_feather', quantity: 1 }, { itemId: 'golden_essence', quantity: 5 }, { itemId: 'dragon_blood', quantity: 2 }]),
    resultItemId: 'huashen_breakthrough_pill',
    resultQuantity: 1,
    baseSuccessRate: 0.15,
    requiredCauldronLevel: 6,
  },
  {
    recipeId: 'heti_breakthrough_pill',
    name: '合体丹',
    description: '辅助合体期突破的仙品丹药',
    level: 20,
    difficulty: 5.0,
    materials: JSON.stringify([{ itemId: 'chaos_essence', quantity: 1 }, { itemId: 'dragon_blood', quantity: 3 }, { itemId: 'phoenix_feather', quantity: 2 }]),
    resultItemId: 'heti_breakthrough_pill',
    resultQuantity: 1,
    baseSuccessRate: 0.1,
    requiredCauldronLevel: 7,
  },
  {
    recipeId: 'medium_juyuan_pill',
    name: '中品聚元丹',
    description: '蕴含浓郁灵气，大幅增加修为',
    level: 8,
    difficulty: 2.0,
    materials: JSON.stringify([{ itemId: 'earth_essence', quantity: 2 }, { itemId: 'spirit_grass', quantity: 5 }, { itemId: 'century_ginseng', quantity: 1 }]),
    resultItemId: 'medium_juyuan_pill',
    resultQuantity: 2,
    baseSuccessRate: 0.55,
    requiredCauldronLevel: 3,
  },
  {
    recipeId: 'high_juyuan_pill',
    name: '上品聚元丹',
    description: '蕴含磅礴灵气，极大增加修为',
    level: 14,
    difficulty: 3.5,
    materials: JSON.stringify([{ itemId: 'golden_essence', quantity: 3 }, { itemId: 'thousand_year_ginseng', quantity: 1 }, { itemId: 'earth_essence', quantity: 5 }]),
    resultItemId: 'high_juyuan_pill',
    resultQuantity: 1,
    baseSuccessRate: 0.3,
    requiredCauldronLevel: 5,
  },
  {
    recipeId: 'defense_supreme_pill',
    name: '金刚丹',
    description: '大幅提升防御力的高级丹药',
    level: 10,
    difficulty: 2.5,
    materials: JSON.stringify([{ itemId: 'earth_essence', quantity: 5 }, { itemId: 'golden_essence', quantity: 2 }, { itemId: 'tiger_bone', quantity: 3 }]),
    resultItemId: 'defense_supreme_pill',
    resultQuantity: 2,
    baseSuccessRate: 0.4,
    requiredCauldronLevel: 4,
  },
  {
    recipeId: 'speed_supreme_pill',
    name: '疾风丹',
    description: '大幅提升速度的高级丹药',
    level: 10,
    difficulty: 2.5,
    materials: JSON.stringify([{ itemId: 'century_ginseng', quantity: 2 }, { itemId: 'blue_lotus', quantity: 5 }, { itemId: 'beast_blood', quantity: 3 }]),
    resultItemId: 'speed_supreme_pill',
    resultQuantity: 2,
    baseSuccessRate: 0.4,
    requiredCauldronLevel: 4,
  },
];

export const alchemyCauldronsData = [
  {
    cauldronId: 'basic_furnace',
    name: '铁制丹炉',
    description: '最基础的丹炉',
    level: 1,
    quality: 'common',
    bonus: JSON.stringify({ successRateBonus: 0, qualityBonus: 0, speedBonus: 0 }),
    obtainMethod: '初始获得',
  },
  {
    cauldronId: 'bronze_furnace',
    name: '青铜丹炉',
    description: '青铜制的丹炉，比铁制更好',
    level: 2,
    quality: 'uncommon',
    bonus: JSON.stringify({ successRateBonus: 0.05, qualityBonus: 0.05, speedBonus: 0.1 }),
    obtainMethod: '商店购买',
  },
  {
    cauldronId: 'spirit_furnace',
    name: '灵纹丹炉',
    description: '刻有灵纹的丹炉',
    level: 3,
    quality: 'rare',
    bonus: JSON.stringify({ successRateBonus: 0.1, qualityBonus: 0.1, speedBonus: 0.2 }),
    obtainMethod: '副本掉落',
  },
  {
    cauldronId: 'earth_fire_furnace',
    name: '地火丹炉',
    description: '以地火为燃料的丹炉',
    level: 5,
    quality: 'epic',
    bonus: JSON.stringify({ successRateBonus: 0.2, qualityBonus: 0.15, speedBonus: 0.3 }),
    obtainMethod: '秘境奖励',
  },
  {
    cauldronId: 'nine_dragon_furnace',
    name: '九龙神炉',
    description: '传说中的神炉，九龙环绕',
    level: 8,
    quality: 'legendary',
    bonus: JSON.stringify({ successRateBonus: 0.4, qualityBonus: 0.3, speedBonus: 0.5 }),
    obtainMethod: '终极奖励',
  },
];
