// 弟子派遣任务种子数据
// 从前端 src/data/disciples/index.ts 迁移

export const expeditionTemplatesData = [
  {
    expeditionId: 'gather_herbs',
    name: '采集灵草',
    description: '前往山林采集炼丹所需的灵草',
    type: 'gather',
    minLevel: 1,
    minDiscipleCount: 1,
    maxDiscipleCount: 3,
    duration: 3600,
    baseRewards: JSON.stringify([
      { type: 'item', itemId: 'spirit_grass', quantity: 5, chance: 1.0 },
      { type: 'exp', quantity: 50, chance: 1.0 },
    ]),
    bonusRewards: JSON.stringify([
      { type: 'item', itemId: 'blood_ginseng', quantity: 1, chance: 0.2 },
      { type: 'item', itemId: 'blue_lotus', quantity: 1, chance: 0.15 },
    ]),
    dangerLevel: 1,
    injuryChance: 0.05,
    requiredTalent: null,
    minTalentValue: null,
  },
  {
    expeditionId: 'mine_ore',
    name: '开采矿石',
    description: '前往矿洞开采炼器所需的矿石',
    type: 'gather',
    minLevel: 2,
    minDiscipleCount: 2,
    maxDiscipleCount: 4,
    duration: 7200,
    baseRewards: JSON.stringify([
      { type: 'item', itemId: 'iron_ore', quantity: 10, chance: 1.0 },
      { type: 'spirit_stone', quantity: 20, chance: 1.0 },
      { type: 'exp', quantity: 80, chance: 1.0 },
    ]),
    bonusRewards: JSON.stringify([
      { type: 'item', itemId: 'spirit_iron', quantity: 2, chance: 0.25 },
      { type: 'item', itemId: 'mithril', quantity: 1, chance: 0.05 },
    ]),
    dangerLevel: 2,
    injuryChance: 0.1,
    requiredTalent: null,
    minTalentValue: null,
  },
  {
    expeditionId: 'explore_ruins',
    name: '探索遗迹',
    description: '探索上古修士遗留的遗迹',
    type: 'explore',
    minLevel: 5,
    minDiscipleCount: 3,
    maxDiscipleCount: 5,
    duration: 14400,
    baseRewards: JSON.stringify([
      { type: 'spirit_stone', quantity: 100, chance: 1.0 },
      { type: 'exp', quantity: 200, chance: 1.0 },
    ]),
    bonusRewards: JSON.stringify([
      { type: 'recipe', itemId: 'random_recipe', quantity: 1, chance: 0.1 },
      { type: 'technique', itemId: 'random_technique', quantity: 1, chance: 0.05 },
      { type: 'item', itemId: 'ancient_artifact', quantity: 1, chance: 0.08 },
    ]),
    dangerLevel: 3,
    injuryChance: 0.2,
    requiredTalent: null,
    minTalentValue: null,
  },
  {
    expeditionId: 'hunt_beasts',
    name: '狩猎妖兽',
    description: '猎杀妖兽获取材料',
    type: 'hunt',
    minLevel: 3,
    minDiscipleCount: 2,
    maxDiscipleCount: 4,
    duration: 10800,
    baseRewards: JSON.stringify([
      { type: 'item', itemId: 'beast_leather', quantity: 5, chance: 1.0 },
      { type: 'item', itemId: 'beast_blood', quantity: 3, chance: 1.0 },
      { type: 'exp', quantity: 150, chance: 1.0 },
    ]),
    bonusRewards: JSON.stringify([
      { type: 'item', itemId: 'beast_core', quantity: 1, chance: 0.3 },
      { type: 'item', itemId: 'rare_material', quantity: 1, chance: 0.1 },
    ]),
    dangerLevel: 3,
    injuryChance: 0.25,
    requiredTalent: 'combat',
    minTalentValue: 40,
  },
  {
    expeditionId: 'secret_realm',
    name: '秘境探险',
    description: '进入神秘秘境寻宝',
    type: 'special',
    minLevel: 10,
    minDiscipleCount: 3,
    maxDiscipleCount: 5,
    duration: 28800,
    baseRewards: JSON.stringify([
      { type: 'spirit_stone', quantity: 500, chance: 1.0 },
      { type: 'exp', quantity: 500, chance: 1.0 },
    ]),
    bonusRewards: JSON.stringify([
      { type: 'item', itemId: 'secret_realm_treasure', quantity: 1, chance: 0.5 },
      { type: 'technique', itemId: 'rare_technique', quantity: 1, chance: 0.1 },
      { type: 'item', itemId: 'legendary_material', quantity: 1, chance: 0.05 },
    ]),
    dangerLevel: 5,
    injuryChance: 0.4,
    requiredTalent: null,
    minTalentValue: null,
  },
];
