// 10章节剧情数据种子
// 设计原则：循序渐进的难度、丰富的分支选择、与游戏系统紧密结合

export const storyChaptersData = [
  {
    chapterId: 'chapter_1',
    name: '第一章：踏入仙途',
    description: '机缘巧合之下，你获得了修仙功法，从此踏上了漫漫仙途。',
    order: 1,
    unlockConditions: null,
    rewards: JSON.stringify([
      { type: 'item', itemId: 'xiaohuandan', value: 5 },
      { type: 'item', itemId: 'lingshi', value: 100 },
      { type: 'cultivation', value: 50 },
    ]),
  },
  {
    chapterId: 'chapter_2',
    name: '第二章：拜入仙门',
    description: '为了获得更好的修炼资源和指导，你决定拜入附近的修仙门派。',
    order: 2,
    unlockConditions: JSON.stringify([
      { type: 'chapter', key: 'chapter_1', operator: '==', value: true },
      { type: 'realm', key: 'level', operator: '>=', value: 2 },
    ]),
    rewards: JSON.stringify([
      { type: 'item', itemId: 'qingyun_pao', value: 1 },
      { type: 'item', itemId: 'lingshi', value: 200 },
      { type: 'technique', itemId: 'qingyun_jue', value: 1 },
    ]),
  },
  {
    chapterId: 'chapter_3',
    name: '第三章：外门历练',
    description: '作为外门弟子，你需要完成各种任务来证明自己的价值。',
    order: 3,
    unlockConditions: JSON.stringify([
      { type: 'chapter', key: 'chapter_2', operator: '==', value: true },
      { type: 'realm', key: 'level', operator: '>=', value: 4 },
    ]),
    rewards: JSON.stringify([
      { type: 'item', itemId: 'juyuandan', value: 10 },
      { type: 'item', itemId: 'qingfengjian', value: 1 },
      { type: 'attribute', itemId: 'comprehension', value: 5 },
    ]),
  },
  {
    chapterId: 'chapter_4',
    name: '第四章：魔影初现',
    description: '门派中接连发生诡异事件，失踪的弟子、神秘的魔气，一切似乎指向一个可怕的阴谋。',
    order: 4,
    unlockConditions: JSON.stringify([
      { type: 'chapter', key: 'chapter_3', operator: '==', value: true },
      { type: 'realm', key: 'name', operator: '==', value: 'zhuji' },
    ]),
    rewards: JSON.stringify([
      { type: 'item', itemId: 'zhujiwan', value: 2 },
      { type: 'item', itemId: 'lingshi', value: 500 },
      { type: 'skill', itemId: 'po_mo_jian', value: 1 },
    ]),
  },
  {
    chapterId: 'chapter_5',
    name: '第五章：金丹之路',
    description: '筑基圆满，是时候冲击金丹期了。但结丹需要的天材地宝何其珍贵，你必须踏上寻宝之旅。',
    order: 5,
    unlockConditions: JSON.stringify([
      { type: 'chapter', key: 'chapter_4', operator: '==', value: true },
      { type: 'realm', key: 'level', operator: '>=', value: 8 },
    ]),
    rewards: JSON.stringify([
      { type: 'item', itemId: 'jindanluyao', value: 1 },
      { type: 'item', itemId: 'hanbing_jian', value: 1 },
      { type: 'attribute', itemId: 'luck', value: 10 },
    ]),
  },
  {
    chapterId: 'chapter_6',
    name: '第六章：秘府探险',
    description: '一张古老的藏宝图揭示了上古大能遗留的秘府位置，无数修士趋之若鹜。',
    order: 6,
    unlockConditions: JSON.stringify([
      { type: 'chapter', key: 'chapter_5', operator: '==', value: true },
      { type: 'realm', key: 'name', operator: '==', value: 'jindan' },
    ]),
    rewards: JSON.stringify([
      { type: 'item', itemId: 'zixiao_jian', value: 1 },
      { type: 'item', itemId: 'shangpinlingshi', value: 100 },
      { type: 'technique', itemId: 'zixiao_shenlei', value: 1 },
    ]),
  },
  {
    chapterId: 'chapter_7',
    name: '第七章：正魔之争',
    description: '魔道势力大举入侵，正道各派联合抵抗。你必须在这场大战中做出自己的选择。',
    order: 7,
    unlockConditions: JSON.stringify([
      { type: 'chapter', key: 'chapter_6', operator: '==', value: true },
      { type: 'realm', key: 'level', operator: '>=', value: 14 },
    ]),
    rewards: JSON.stringify([
      { type: 'item', itemId: 'pojiaodan', value: 3 },
      { type: 'item', itemId: 'jinling_jia', value: 1 },
      { type: 'attribute', itemId: 'karma', value: 20 },
    ]),
  },
  {
    chapterId: 'chapter_8',
    name: '第八章：元婴之劫',
    description: '金丹化婴，是修士生涯的又一重大关卡。这一步，九死一生。',
    order: 8,
    unlockConditions: JSON.stringify([
      { type: 'chapter', key: 'chapter_7', operator: '==', value: true },
      { type: 'realm', key: 'level', operator: '>=', value: 12 },
    ]),
    rewards: JSON.stringify([
      { type: 'item', itemId: 'taiyi_jian', value: 1 },
      { type: 'item', itemId: 'xumingdan', value: 2 },
      { type: 'attribute', itemId: 'lifespan', value: 500 },
    ]),
  },
  {
    chapterId: 'chapter_9',
    name: '第九章：因果轮回',
    description: '过去种下的因，如今结成了果。是时候面对那些尘封的恩怨了。',
    order: 9,
    unlockConditions: JSON.stringify([
      { type: 'chapter', key: 'chapter_8', operator: '==', value: true },
      { type: 'realm', key: 'name', operator: '==', value: 'yuanying' },
    ]),
    rewards: JSON.stringify([
      { type: 'item', itemId: 'xuanwu_jia', value: 1 },
      { type: 'item', itemId: 'hunyuandan', value: 1 },
      { type: 'attribute', itemId: 'comprehension', value: 20 },
    ]),
  },
  {
    chapterId: 'chapter_10',
    name: '第十章：飞升之路',
    description: '修为通天，天劫将至。渡过此劫，便可飞升仙界；若是失败，则是形神俱灭。',
    order: 10,
    unlockConditions: JSON.stringify([
      { type: 'chapter', key: 'chapter_9', operator: '==', value: true },
      { type: 'realm', key: 'name', operator: '==', value: 'huashen' },
    ]),
    rewards: JSON.stringify([
      { type: 'item', itemId: 'huntian_jian', value: 1 },
      { type: 'item', itemId: 'hundun_pao', value: 1 },
      { type: 'title', itemId: 'feisheng_xianren', value: 1 },
    ]),
  },
];

// 第一章剧情节点
export const chapter1Nodes = [
  {
    nodeId: 'ch1_start',
    chapterId: 'chapter_1',
    type: 'NARRATION',
    order: 1,
    content: '你是一个普通人，生活在凡尘俗世之中。直到那一天，命运的齿轮开始转动...',
    nextNodeId: 'ch1_discovery',
  },
  {
    nodeId: 'ch1_discovery',
    chapterId: 'chapter_1',
    type: 'NARRATION',
    order: 2,
    content: '在一次意外中，你发现了一本泛黄的古籍。书页上的文字散发着淡淡的光芒，似乎蕴含着某种神秘的力量。',
    nextNodeId: 'ch1_choice_1',
  },
  {
    nodeId: 'ch1_choice_1',
    chapterId: 'chapter_1',
    type: 'CHOICE',
    order: 3,
    content: '你要如何处置这本古籍？',
    choices: JSON.stringify([
      {
        text: '仔细研读，探索其中奥秘',
        nextNodeId: 'ch1_study',
        effects: [{ type: 'modify_attribute', target: 'comprehension', value: 5 }],
      },
      {
        text: '谨慎收好，找个安全的地方再看',
        nextNodeId: 'ch1_careful',
        effects: [{ type: 'modify_attribute', target: 'luck', value: 3 }],
      },
      {
        text: '这可能是邪物，最好烧掉',
        nextNodeId: 'ch1_burn',
        effects: [],
      },
    ]),
  },
  {
    nodeId: 'ch1_study',
    chapterId: 'chapter_1',
    type: 'NARRATION',
    order: 4,
    content: '你迫不及待地翻开古籍，发现这是一本名为《太初引气诀》的修炼功法。书中详细记载了引气入体、踏入仙途的法门。',
    nextNodeId: 'ch1_first_cultivation',
    effects: JSON.stringify([{ type: 'set_flag', target: 'eager_learner', value: true }]),
  },
  {
    nodeId: 'ch1_careful',
    chapterId: 'chapter_1',
    type: 'NARRATION',
    order: 4,
    content: '你小心翼翼地将古籍藏好，等到夜深人静时才取出研读。这是一本名为《太初引气诀》的修炼功法。',
    nextNodeId: 'ch1_first_cultivation',
    effects: JSON.stringify([{ type: 'set_flag', target: 'cautious_nature', value: true }]),
  },
  {
    nodeId: 'ch1_burn',
    chapterId: 'chapter_1',
    type: 'NARRATION',
    order: 4,
    content: '你正要将古籍丢入火中，书页突然自动翻开，一道柔和的光芒笼罩了你。冥冥中，你似乎听到了一个声音："既有仙缘，何故自弃？"',
    nextNodeId: 'ch1_forced_fate',
  },
  {
    nodeId: 'ch1_forced_fate',
    chapterId: 'chapter_1',
    type: 'NARRATION',
    order: 5,
    content: '古籍落回你的手中，书页翻到了第一章——《太初引气诀》。看来，这份机缘你无论如何都躲不掉了。',
    nextNodeId: 'ch1_first_cultivation',
    effects: JSON.stringify([{ type: 'set_flag', target: 'forced_fate', value: true }]),
  },
  {
    nodeId: 'ch1_first_cultivation',
    chapterId: 'chapter_1',
    type: 'NARRATION',
    order: 6,
    content: '你按照功法所述，盘膝而坐，调整呼吸，尝试感应天地间的灵气。起初什么也感觉不到，但渐渐地，你似乎触碰到了某种玄妙的存在。',
    nextNodeId: 'ch1_spiritual_root',
  },
  {
    nodeId: 'ch1_spiritual_root',
    chapterId: 'chapter_1',
    type: 'NARRATION',
    order: 7,
    content: '一丝若有若无的气息在你体内流转，带来一种说不出的舒泰感。这便是灵根显现的征兆！看来你并非毫无修仙资质。',
    nextNodeId: 'ch1_first_battle',
  },
  {
    nodeId: 'ch1_first_battle',
    chapterId: 'chapter_1',
    type: 'NARRATION',
    order: 8,
    content: '就在你沉浸于修炼之时，屋外传来了异响。你警觉地走出门，发现一只散发着妖气的灵狼正虎视眈眈地盯着你。',
    nextNodeId: 'ch1_battle_1',
  },
  {
    nodeId: 'ch1_battle_1',
    chapterId: 'chapter_1',
    type: 'BATTLE',
    order: 9,
    content: '灵狼扑了上来！这是你修仙以来的第一场战斗。',
    enemyIds: JSON.stringify(['ling_lang_lv1']),
    battleRewards: JSON.stringify([
      { type: 'item', itemId: 'langya', value: 1 },
      { type: 'exp', value: 20 },
    ]),
    nextNodeId: 'ch1_after_battle',
  },
  {
    nodeId: 'ch1_after_battle',
    chapterId: 'chapter_1',
    type: 'NARRATION',
    order: 10,
    content: '你击败了灵狼，获得了它的獠牙作为战利品。这场战斗让你意识到，修仙之路充满危险，必须不断变强才能生存。',
    nextNodeId: 'ch1_choice_2',
  },
  {
    nodeId: 'ch1_choice_2',
    chapterId: 'chapter_1',
    type: 'CHOICE',
    order: 11,
    content: '经过这场战斗，你对未来的道路有了新的思考。',
    choices: JSON.stringify([
      {
        text: '实力为尊，唯有变强才能掌控命运',
        nextNodeId: 'ch1_path_power',
        effects: [
          { type: 'modify_attribute', target: 'attack', value: 5 },
          { type: 'set_flag', target: 'path_power', value: true },
        ],
      },
      {
        text: '修炼是为了长生，战斗不过是手段',
        nextNodeId: 'ch1_path_longevity',
        effects: [
          { type: 'modify_attribute', target: 'maxHp', value: 20 },
          { type: 'set_flag', target: 'path_longevity', value: true },
        ],
      },
      {
        text: '修仙问道，探索天地奥秘才是正途',
        nextNodeId: 'ch1_path_dao',
        effects: [
          { type: 'modify_attribute', target: 'comprehension', value: 3 },
          { type: 'set_flag', target: 'path_dao', value: true },
        ],
      },
    ]),
  },
  {
    nodeId: 'ch1_path_power',
    chapterId: 'chapter_1',
    type: 'NARRATION',
    order: 12,
    content: '力量，只有足够的力量才能让你在这个弱肉强食的世界立足。你决心走上一条以战养战的修炼之路。',
    nextNodeId: 'ch1_ending',
  },
  {
    nodeId: 'ch1_path_longevity',
    chapterId: 'chapter_1',
    type: 'NARRATION',
    order: 12,
    content: '长生不老，超脱轮回，这才是修仙的真谛。你决心稳扎稳打，追求大道永恒。',
    nextNodeId: 'ch1_ending',
  },
  {
    nodeId: 'ch1_path_dao',
    chapterId: 'chapter_1',
    type: 'NARRATION',
    order: 12,
    content: '天地间蕴含着无穷的奥秘，修仙不仅是变强，更是一场对宇宙真理的探索。你决心走上求道之路。',
    nextNodeId: 'ch1_ending',
  },
  {
    nodeId: 'ch1_ending',
    chapterId: 'chapter_1',
    type: 'NARRATION',
    order: 13,
    content: '从这一夜起，你的人生彻底改变。凡人蜕变，仙途开启。但你知道，这只是漫漫仙路的第一步...',
    effects: JSON.stringify([{ type: 'set_flag', target: 'chapter_1_completed', value: true }]),
  },
];

// 第二章剧情节点
export const chapter2Nodes = [
  {
    nodeId: 'ch2_start',
    chapterId: 'chapter_2',
    type: 'NARRATION',
    order: 1,
    content: '独自修炼数月后，你发现进度越来越慢。功法有限、资源匮乏，你意识到必须寻找更好的修炼环境。',
    nextNodeId: 'ch2_info',
  },
  {
    nodeId: 'ch2_info',
    chapterId: 'chapter_2',
    type: 'NARRATION',
    order: 2,
    content: '打听之下，你得知百里外有一座名为"青云宗"的修仙门派，每年都会招收新弟子。下一次招收就在半月之后。',
    nextNodeId: 'ch2_journey',
  },
  {
    nodeId: 'ch2_journey',
    chapterId: 'chapter_2',
    type: 'NARRATION',
    order: 3,
    content: '你收拾行囊，踏上了前往青云宗的旅程。一路上，你看到了许多同样怀揣着仙途梦想的年轻人。',
    nextNodeId: 'ch2_meet_liu',
  },
  {
    nodeId: 'ch2_meet_liu',
    chapterId: 'chapter_2',
    type: 'DIALOGUE',
    order: 4,
    speaker: '刘青',
    content: '哟，又是一个去青云宗碰运气的？我叫刘青，家里世代都是凡人，这次豁出去了想搏一个仙缘。你呢？',
    nextNodeId: 'ch2_choice_liu',
  },
  {
    nodeId: 'ch2_choice_liu',
    chapterId: 'chapter_2',
    type: 'CHOICE',
    order: 5,
    content: '刘青似乎是个热情的人，你要如何回应？',
    choices: JSON.stringify([
      {
        text: '如实相告，交个朋友',
        nextNodeId: 'ch2_friend_liu',
        effects: [
          { type: 'set_flag', target: 'liu_friend', value: true },
          { type: 'modify_attribute', target: 'luck', value: 2 },
        ],
      },
      {
        text: '随意敷衍，独行更自在',
        nextNodeId: 'ch2_alone',
        effects: [{ type: 'set_flag', target: 'lone_wolf', value: true }],
      },
    ]),
  },
  {
    nodeId: 'ch2_friend_liu',
    chapterId: 'chapter_2',
    type: 'NARRATION',
    order: 6,
    content: '你与刘青结伴而行，一路上互相照应。他虽然没有修为，但见多识广，告诉了你许多关于青云宗的情报。',
    nextNodeId: 'ch2_arrive',
    effects: JSON.stringify([{ type: 'add_item', target: 'qingyunlingpai', value: 1 }]),
  },
  {
    nodeId: 'ch2_alone',
    chapterId: 'chapter_2',
    type: 'NARRATION',
    order: 6,
    content: '你婉拒了刘青的好意，独自前行。修仙之路本就是一条孤独的道路，太多牵绊反而是累赘。',
    nextNodeId: 'ch2_arrive',
  },
  {
    nodeId: 'ch2_arrive',
    chapterId: 'chapter_2',
    type: 'NARRATION',
    order: 7,
    content: '青云宗坐落于青云峰之上，云雾缭绕间可见殿宇楼阁错落有致。宗门山门前已经聚集了上千名想要拜入仙门的年轻人。',
    nextNodeId: 'ch2_test_intro',
  },
  {
    nodeId: 'ch2_test_intro',
    chapterId: 'chapter_2',
    type: 'DIALOGUE',
    order: 8,
    speaker: '青云宗执事',
    content: '青云宗入门考核分为三关：第一关测试灵根资质，第二关考验心性，第三关是实战比试。通过三关者方可入门。',
    nextNodeId: 'ch2_test_1',
  },
  {
    nodeId: 'ch2_test_1',
    chapterId: 'chapter_2',
    type: 'NARRATION',
    order: 9,
    content: '第一关：灵根测试。你将手放在测灵石上，石头散发出柔和的光芒，显示出你的灵根资质。执事点了点头，示意你通过。',
    nextNodeId: 'ch2_test_2',
    effects: JSON.stringify([{ type: 'set_flag', target: 'test_1_passed', value: true }]),
  },
  {
    nodeId: 'ch2_test_2',
    chapterId: 'chapter_2',
    type: 'NARRATION',
    order: 10,
    content: '第二关：心境考验。你被带入一个幻境之中，需要在各种诱惑和恐惧面前保持本心。',
    nextNodeId: 'ch2_illusion',
  },
  {
    nodeId: 'ch2_illusion',
    chapterId: 'chapter_2',
    type: 'CHOICE',
    order: 11,
    content: '幻境中，你看到了自己最渴望的东西，同时也面对着最深的恐惧。你会如何应对？',
    choices: JSON.stringify([
      {
        text: '这些都是幻象，我心如止水',
        nextNodeId: 'ch2_calm_heart',
        effects: [
          { type: 'modify_attribute', target: 'comprehension', value: 5 },
          { type: 'set_flag', target: 'calm_heart', value: true },
        ],
      },
      {
        text: '直面恐惧，战胜心魔',
        nextNodeId: 'ch2_face_fear',
        effects: [
          { type: 'modify_attribute', target: 'attack', value: 5 },
          { type: 'set_flag', target: 'brave_heart', value: true },
        ],
      },
      {
        text: '承认欲望，但不被其控制',
        nextNodeId: 'ch2_accept_desire',
        effects: [
          { type: 'modify_attribute', target: 'luck', value: 5 },
          { type: 'set_flag', target: 'honest_heart', value: true },
        ],
      },
    ]),
  },
  {
    nodeId: 'ch2_calm_heart',
    chapterId: 'chapter_2',
    type: 'NARRATION',
    order: 12,
    content: '你心如古井，任凭幻象如何变换，都无法动摇你分毫。考官赞许地点头：心境上佳，通过。',
    nextNodeId: 'ch2_test_3',
  },
  {
    nodeId: 'ch2_face_fear',
    chapterId: 'chapter_2',
    type: 'NARRATION',
    order: 12,
    content: '你直面内心的恐惧，与心魔激战一场。虽然过程艰难，但最终你战胜了自己。考官点头：勇气可嘉，通过。',
    nextNodeId: 'ch2_test_3',
  },
  {
    nodeId: 'ch2_accept_desire',
    chapterId: 'chapter_2',
    type: 'NARRATION',
    order: 12,
    content: '你坦然承认自己的欲望，但明确表示不会被其奴役。考官微笑：知己知彼，不失本心，通过。',
    nextNodeId: 'ch2_test_3',
  },
  {
    nodeId: 'ch2_test_3',
    chapterId: 'chapter_2',
    type: 'NARRATION',
    order: 13,
    content: '第三关：实战比试。你被安排与另一名考生对战，胜者入门，败者离去。你的对手是一个身材魁梧的青年。',
    nextNodeId: 'ch2_battle',
  },
  {
    nodeId: 'ch2_battle',
    chapterId: 'chapter_2',
    type: 'BATTLE',
    order: 14,
    content: '比试开始！对手率先发起攻击。',
    enemyIds: JSON.stringify(['candidate_lv3']),
    battleRewards: JSON.stringify([{ type: 'exp', value: 50 }]),
    nextNodeId: 'ch2_victory',
  },
  {
    nodeId: 'ch2_victory',
    chapterId: 'chapter_2',
    type: 'NARRATION',
    order: 15,
    content: '经过一番激战，你击败了对手。围观的弟子们发出惊叹，执事上前宣布：恭喜你，从今日起你便是青云宗的外门弟子了！',
    nextNodeId: 'ch2_ending',
  },
  {
    nodeId: 'ch2_ending',
    chapterId: 'chapter_2',
    type: 'NARRATION',
    order: 16,
    content: '你换上了青云宗的弟子服，领取了修炼资源和住所钥匙。仙门弟子的生涯正式开始！',
    effects: JSON.stringify([
      { type: 'set_flag', target: 'chapter_2_completed', value: true },
      { type: 'add_item', target: 'qingyun_pao', value: 1 },
    ]),
  },
];

// 导出所有章节节点数据
export const allChapterNodes = [
  ...chapter1Nodes,
  ...chapter2Nodes,
  // 后续章节节点可以类似添加...
];
